data_directory = '/var/lib/postgresql/data'
hba_file = '/etc/postgresql/pg_hba.conf'
listen_addresses = '127.0.0.1'
port = 5432
unix_socket_directories = '/run/postgresql'
max_connections = 20
shared_buffers = '32MB'
statement_timeout = '3s'
log_destination = 'stderr'
logging_collector = off
log_line_prefix = '%m [%p] '
